const seed=[{id:'imperial',name:'Mate Imperial',type:'Mate',price:48500,stock:6,description:'Calabaza seleccionada, virola dorada.',featured:true},{id:'camionero',name:'Mate Camionero',type:'Mate',price:38900,stock:9,description:'Cuero natural y base reforzada.',featured:true},{id:'alpaca',name:'Bombilla de Alpaca',type:'Bombilla',price:16200,stock:14,description:'Pico curvo y filtro desmontable.',featured:false},{id:'combo',name:'Combo Ruta',type:'Combo',price:76500,stock:3,description:'Mate, bombilla y termo para llevar.',featured:true},{id:'termo',name:'Termo Acero 1L',type:'Termo',price:52400,stock:7,description:'Doble pared, conserva la temperatura.',featured:false}];
const $=s=>document.querySelector(s); const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n);
let products=JSON.parse(localStorage.getItem('mw-products')||'null')||seed, cart=JSON.parse(localStorage.getItem('mw-cart')||'[]'), settings=JSON.parse(localStorage.getItem('mw-settings')||'{"whatsapp":"5491100000000","instagram":"mateswell"}'), orders=JSON.parse(localStorage.getItem('mw-orders')||'[]');
function persist(){localStorage.setItem('mw-products',JSON.stringify(products));localStorage.setItem('mw-cart',JSON.stringify(cart));localStorage.setItem('mw-settings',JSON.stringify(settings));localStorage.setItem('mw-orders',JSON.stringify(orders))} function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2500)}
function renderProducts(){let f=$('#category').value;$('#products').innerHTML=products.filter(p=>f==='all'||p.type===f).filter(p=>p.stock>0).map(p=>`<article class="product"><div class="product-image" aria-label="Imagen de referencia de ${p.name}" role="img">◒</div><div class="product-info"><p>${p.type}${p.featured?' · Destacado':''}</p><h3>${p.name}</h3><p>${p.description}</p><div class="price"><span>${money(p.price)}</span><button data-add="${p.id}" aria-label="Agregar ${p.name}">Agregar</button></div></div></article>`).join('')||'<p>No hay productos en esta categoría.</p>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add))}
function add(id){let p=products.find(x=>x.id===id), line=cart.find(x=>x.id===id);if(line){if(line.qty>=p.stock)return toast('No hay más unidades disponibles');line.qty++}else cart.push({id,qty:1});persist();renderCart();toast('Producto agregado a tu bolsa')}
function renderCart(){let count=cart.reduce((n,x)=>n+x.qty,0),total=cart.reduce((n,x)=>n+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0);$('.bag b').textContent=count;$('#total').textContent=money(total);$('#cartItems').innerHTML=cart.map(l=>{let p=products.find(x=>x.id===l.id);return p?`<div class="cart-item"><b>${p.name}</b><span>${l.qty} × ${money(p.price)}</span><button data-remove="${p.id}">Quitar</button></div>`:''}).join('')||'<p class="muted">Todavía no agregaste productos.</p>';document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==b.dataset.remove);persist();renderCart()})}
function renderAdmin(){let revenue=orders.reduce((n,o)=>n+o.total,0),units=orders.reduce((n,o)=>n+o.items.reduce((a,i)=>a+i.qty,0),0);$('#revenue').textContent=money(revenue);$('#ordersCount').textContent=orders.length;$('#units').textContent=units;$('#adminProducts').innerHTML=products.map(p=>`<div class="admin-list"><span><b>${p.name}</b><small>${money(p.price)} · stock ${p.stock}${p.featured?' · destacado':''}</small></span><span><button data-edit="${p.id}">Editar</button> <button data-delete="${p.id}">Eliminar</button></span></div>`).join('');$('#orders').innerHTML=orders.map(o=>`<div class="order"><span><b>${o.id}</b><small>${o.date} · ${o.items.map(i=>`${i.qty} ${products.find(p=>p.id===i.id)?.name||'producto'}`).join(', ')}</small></span><span>${money(o.total)}<select data-status="${o.id}">${['Pendiente','Confirmado','Preparando','Enviado','Entregado'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></span></div>`).join('')||'<p class="empty">Aún no hay pedidos registrados.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{products=products.filter(p=>p.id!==b.dataset.delete);persist();renderProducts();renderAdmin();toast('Producto eliminado')});document.querySelectorAll('[data-status]').forEach(s=>s.onchange=()=>{orders.find(o=>o.id===s.dataset.status).status=s.value;persist();toast('Estado actualizado')})}
function edit(id){let p=products.find(p=>p.id===id);for(let k of ['id','name','type','price','stock','description','featured']){let el=$('#product'+(k==='id'?'Id':'') )||$('#'+k);if(el)el[k==='featured'?'checked':'value']=p[k]}window.location.hash='admin'}
$('.bag').onclick=()=>{$('#cart').classList.add('open');$('#cart').setAttribute('aria-hidden','false')};$('.close').onclick=()=>{$('#cart').classList.remove('open');$('#cart').setAttribute('aria-hidden','true')};$('.menu').onclick=()=>$('nav').classList.toggle('open');$('#category').onchange=renderProducts;
$('#checkout').onclick=()=>{if(!cart.length)return toast('Tu bolsa está vacía');let total=cart.reduce((n,x)=>n+products.find(p=>p.id===x.id).price*x.qty,0),o={id:'MW-'+Date.now().toString().slice(-6),date:new Date().toLocaleDateString('es-AR'),items:cart,total,status:'Pendiente'};orders.unshift(o);cart.forEach(l=>products.find(p=>p.id===l.id).stock-=l.qty);cart=[];persist();renderCart();renderProducts();if(!$('#dashboard').hidden)renderAdmin();let message=`Hola, quiero confirmar el pedido ${o.id}:\n${o.items.map(i=>`${i.qty}x ${products.find(p=>p.id===i.id).name}`).join('\n')}\nTotal: ${money(total)}`;window.open(`https://wa.me/${settings.whatsapp}?text=${encodeURIComponent(message)}`,'_blank');toast('Pedido registrado; abrimos WhatsApp')};
$('#loginForm').onsubmit=e=>{e.preventDefault();if($('#password').value!=='mateswell-demo')return toast('Contraseña incorrecta');sessionStorage.setItem('mw-admin','1');showAdmin()};function showAdmin(){let on=sessionStorage.getItem('mw-admin');$('#login').hidden=!!on;$('#dashboard').hidden=!on;$('#logout').hidden=!on;if(on)renderAdmin()}$('#logout').onclick=()=>{sessionStorage.removeItem('mw-admin');showAdmin()};
$('#productForm').onsubmit=e=>{e.preventDefault();let id=$('#productId').value||crypto.randomUUID(),p={id,name:$('#name').value,type:$('#type').value,price:+$('#price').value,stock:+$('#stock').value,description:$('#description').value,featured:$('#featured').checked};let i=products.findIndex(x=>x.id===id);if(i>-1)products[i]=p;else products.push(p);e.target.reset();$('#productId').value='';persist();renderProducts();renderAdmin();toast('Producto guardado')};$('#settingsForm').onsubmit=e=>{e.preventDefault();settings.whatsapp=$('#whatsapp').value.replace(/\D/g,'');settings.instagram=$('#instagram').value.replace(/^@/,'');persist();links();toast('Configuración guardada')};function links(){$('#whatsapp').value=settings.whatsapp;$('#instagram').value=settings.instagram;$('#footerWhatsapp').href=`https://wa.me/${settings.whatsapp}`;$('#footerInstagram').href=`https://instagram.com/${settings.instagram}`}
$('#year').textContent=new Date().getFullYear();links();renderProducts();renderCart();showAdmin();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
